### ISSUE TITLE
The generation of keywords.json

### ISSUE THREAD

**Issue by nimasteryang** [shangqing-liu/ContraBERT#1]
Hi Author, 

Thanks for providing the replication packages. However, I encounter a problem when trying to replicate your work. When I was trying to generate mutation for code, I find that the code in [parser/scripts/mutations.py](https://github.com/shangqing-liu/ContraBERT/blob/14372ccd567344cffa410e2813cc2adb94b706e2/code%20search/parser/scripts/mutation.py#L358) have a missing file of `./data/vocabs/keywords.json`, can you please provide the file or the way to generate this file? Thank you so much!

**Comment by shangqing-liu** [comment]
Hi, thanks for your attention to our work. The vocab set is generated from the pre-training dataset as our paper claims. I have deleted these scripts and committed another version in this repo since they are not used in the task of code search.
Thank you.
