### ISSUE TITLE
Some questions for model training.

### ISSUE THREAD

**Issue by yetlinghao** [shangqing-liu/ContraBERT#3]
Hi author,I'm a beginner in deep learning so the next question I'm asking might be a bit silly ;)

When I reading your ContraBERT paper,I'm confused that how to combine two training objectives.
As said in this paper,M and M' separated in training.Is M's training objective only MLM? Is M's parameter update not affected by the contrastive learning part?

**Comment by shangqing-liu** [comment]
Thanks for your attention to our work. M' updates its parameters by momentum and M updates its parameters by gradient descent. we use M as our ContraBERT. M' training objective is not MLM, we use InfoNCE as the training objective.
